# Generated by Django 3.2.6 on 2021-08-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('type', models.CharField(choices=[('Dance', 'Dance'), ('Programming', 'Programming'), ('Language', 'Language')], default='Dance', max_length=15)),
                ('due_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('students', models.JSONField()),
            ],
        ),
    ]
